### ISSUE TITLE
SSL Error when using Django extenions' runserver_plus

### ISSUE THREAD

**Issue by a14d** [adamchainz/django-browser-reload#126]
### Python Version

3.10.8

### Django Version

4.1.3

### Browser

Chromium: Version 107.0.5304.87 (Official Build) Arch Linux (64-bit)

### Description

Hi Adam,

Thanks for this awesome and helpful tool.

A problem come when I use it with the `runserver_plus`:

```shell
python manage.py runserver_plus localhost:8000 --cert-file certs/localhost.crt --key-file certs/localhost.key --nostatic --settings=config.settings.dev
```

It shows:

```shell
127.0.0.1 - - [03/Nov/2022 13:18:13] "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 -
Error on request:
Traceback (most recent call last):
  File "/home/me/.local/share/virtualenvs/django-starter-xnFyc4Yx/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/home/me/.local/share/virtualenvs/django-starter-xnFyc4Yx/lib/python3.10/site-packages/werkzeug/serving.py", line 325, in execute
    write(data)
  File "/home/me/.local/share/virtualenvs/django-starter-xnFyc4Yx/lib/python3.10/site-packages/werkzeug/serving.py", line 298, in write
    self.wfile.write(b"\r\n")
  File "/usr/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)
```

When I remove the `django_browser_reload` from the INSTALLED_APPS, the problem disappear.

---
Django version: 4.1.3
Python version: 3.10.8 (main, Oct 13 2022, 21:13:48) [GCC 12.2.0] [x86_64-Linux-5.15.76-1-MANJARO]

**Comment by adamchainz** [comment]
This bug must be in the SSL implementation in werkzeug, or the way djagno-extensions uses it. It’s probably just triggered by django-browser-reload’s use of a streaming HTTP response, which is a little rare but perfectly allowed.

(I recommmend against using django-extensions, it's unfortunately not very well maintained.)
